import { DEFAULT_INITIAL_STATE, loadInitialState } from './Controllers';
import { embedState, makeState } from '../TestUtils/State';

it('loads the same report contract generated by the Go backend', () => {
  const state = makeState();
  embedState(state);
  expect(loadInitialState()).toEqual(state);
});
it('falls back when the state element is absent', () => {
  expect(loadInitialState()).toEqual(DEFAULT_INITIAL_STATE);
});
it.each([
  '',
  'invalid',
  'null',
  '[]',
  '42',
  '{}',
  '{"config":{},"createdAt":42}',
  '{"config":{"services":null},"serviceCoverages":null,"logicalServiceCoverages":null}'
])('handles invalid or incomplete report data: %s', (json) => {
  embedState(json);
  expect(loadInitialState()).toEqual(DEFAULT_INITIAL_STATE);
});
